name: conventional-pr-title-alt
author: Zer0touch <shocker@Zer0touch.co.uk>
description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
inputs:
  success-state:
    description: Description of the status check if validation succeeds.
    required: true
    default: Title follows the specification.
  failure-state:
    description: Description of the status check if validation fails.
    required: true
    default: Title does not follow the specification.
  context-name:
    description: Persistent status check context key
    required: true
    default: conventional-pr-title
  preset:
    description: Conventional changelog preset to use.
    required: true
    default: conventional-changelog-angular
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield
  color: green
